#!/usr/bin/env php
<?php

/**
 * @file
 * Script to run one step of the Drupal CMS installation.
 *
 * This version specifically targets the Haven site template by pre-filling
 * the recipe selection via GET parameters.
 */

use Drupal\RecipeKit\Installer\Hooks;

$_GET['rewrite'] = 'ok';
$_GET['site_name'] = 'Drupal CMS Haven';
$_GET['template'] = '1';
// Inject the Haven recipe into the installer's task list.
$_GET['recipes'] = ['drupal/haven'];

register_shutdown_function('_install_drupal_cms_profile_modules');

function _install_drupal_cms_profile_modules() {
  global $install_state;
  if ($install_state['base_system_verified']) {
    // Explicitly set the recipes in the install state before batch processing.
    $install_state['parameters']['recipes'] = ['drupal/haven'];

    batch_set(Hooks::applyRecipes($install_state));
    $batch = &batch_get();
    $batch['progressive'] = FALSE;
    batch_process();
    \Drupal::state()->set('recipe_installer_kit.profile_modules_installed', TRUE);
  }
}

chdir(dirname(__DIR__) . '/web/core');
ob_start(fn($buffer, $phase) => TRUE, 1);
include 'install.php';
